=== jeap-admin-ch/jeap-process-context-service/jeap-process-context-repository-template-json/src/main/schema/process-template-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "$ref": "#/definitions/processTemplate",
  "definitions": {
    "message": {
      "type": "object",
      "properties": {
        "messageName": {
          "type": "string"
        },
        "topicName": {
          "type": "string"
        },
        "clusterName": {
          "type": "string"
        },
        "correlationProvider": {
          "type": "string"
        },
        "payloadExtractor": {
          "type": "string"
        },
        "referenceExtractor": {
          "type": "string"
        },
        "correlatedBy": {
          "$ref": "#/definitions/correlatedByProcessData"
        },
        "triggersProcessInstantiation": {
          "type": "boolean"
        },
        "processInstantiationCondition": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "messageName",
        "topicName"
      ]
    },
    "processTemplate": {
      "properties": {
        "name": {
          "type": "string"
        },
        "tasks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/task"
          }
        },
        "messages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/message"
          }
        },
        "processData": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/processData"
          }
        },
        "relationSystemId": {
          "type": "string"
        },
        "relationPatterns": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/relationPatterns"
          }
        },
        "completions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/completion"
          }
        },
        "snapshots": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/snapshot"
          }
        }
      },
      "required": [
        "name",
        "tasks"
      ],
      "additionalProperties": false
    },
    "processData": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "source": {
          "$ref": "#/definitions/source"
        }
      },
      "additionalProperties": false,
      "required": [
        "key",
        "source"
      ]
    },
    "source": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "messageDataKey": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "message",
        "messageDataKey"
      ]
    },
    "reachedWhen": {
      "type": "object",
      "oneOf": [
        {
          "$ref": "#/definitions/reachedWhenCondition"
        },
        {
          "$ref": "#/definitions/reachedWhenTasksCompleted"
        }
      ]
    },
    "reachedWhenCondition": {
      "properties": {
        "condition": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "condition"
      ]
    },
    "reachedWhenTasksCompleted": {
      "properties": {
        "tasksCompleted": {
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "additionalProperties": false,
      "required": [
        "tasksCompleted"
      ]
    },
    "completedBy": {
      "$ref": "#/definitions/completedByMessage"
    },
    "completedByMessage": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false
    },
    "task": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "lifecycle": {
          "type": "string",
          "enum": [
            "static",
            "dynamic",
            "observed"
          ]
        },
        "cardinality": {
          "type": "string",
          "enum": [
            "single-instance",
            "multi-instance",
            "single",
            "dynamic"
          ]
        },
        "completedBy": {
          "type": "object",
          "$ref": "#/definitions/completedBy"
        },
        "plannedBy": {
          "type": "object",
          "properties": {
            "message": {
              "type": "string"
            },
            "condition": {
              "type": "string"
            }
          }
        },
        "observes": {
          "type": "object",
          "properties": {
            "message": {
              "type": "string"
            },
            "condition": {
              "type": "string"
            }
          }
        },
        "taskData": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/taskData"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "name"
      ]
    },
    "relationPatterns": {
      "type": "object",
      "properties": {
        "object": {
          "type": "object",
          "$ref": "#/definitions/relationNode"
        },
        "subject": {
          "type": "object",
          "$ref": "#/definitions/relationNode"
        },
        "predicateType": {
          "type": "string"
        },
        "joinType": {
          "type": "string",
          "enum": ["byValue", "byRole"]
        },
        "featureFlag": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "object",
        "subject",
        "predicateType"
      ]
    },
    "relationNode": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "selector": {
          "type": "object",
          "$ref": "#/definitions/relationNodeSelector"
        }
      },
      "additionalProperties": false,
      "required": [
        "type",
        "selector"
      ]
    },
    "relationNodeSelector": {
      "type": "object",
      "properties": {
        "processDataKey": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "processDataKey"
      ]
    },
    "correlatedByProcessData": {
      "type": "object",
      "properties": {
        "processDataKey": {
          "type": "string"
        },
        "messageDataKey": {
          "type": "string"
        }
      },
      "required": [
        "processDataKey",
        "messageDataKey"
      ],
      "additionalProperties": false
    },
    "completion": {
      "type": "object",
      "properties": {
        "completedBy": {
          "type": "object",
          "$ref": "#/definitions/completionCondition"
        }
      },
      "additionalProperties": false,
      "required": [
        "completedBy"
      ]
    },
    "completionCondition": {
      "type": "object",
      "properties": {
        "condition": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "conclusion": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "snapshot": {
      "type": "object",
      "properties": {
        "createdOn": {
          "type": "object",
          "$ref": "#/definitions/snapshotCondition"
        }
      },
      "additionalProperties": false,
      "required": [
        "createdOn"
      ]
    },
    "snapshotCondition": {
      "type": "object",
      "properties": {
        "completion": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "taskData": {
      "type": "object",
      "properties": {
        "sourceMessage": {
          "type": "string"
        },
        "messageDataKeys": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": [ "sourceMessage", "messageDataKeys" ]
    }
  }
}

=== jeap-admin-ch/jeap-process-context-service/jeap-process-context-scs/src/test/resources/process/templates/completions.json
{
  "name": "completions",
  "tasks": [
    {
      "name": "mandatory",
      "completedBy": {
        "message": "Test3Event"
      }
    }
  ],
  "messages": [
    {
      "messageName": "Test1Event",
      "topicName": "topic.test1",
      "payloadExtractor": "ch.admin.bit.jeap.processcontext.testevent.Test1EventPayloadExtractor",
      "triggersProcessInstantiation": true
    },
    {
      "messageName": "Test2Event",
      "topicName": "topic.test2",
      "triggersProcessInstantiation": true
    },
    {
      "messageName": "Test3Event",
      "topicName": "topic.test3",
      "triggersProcessInstantiation": true
    }
  ],
  "completions": [
    {
      "completedBy" : {
        "condition" : "ch.admin.bit.jeap.processcontext.processcompletion.Event1GotchaInDataKey1ProcessCompletionCondition"
      }
    },
    {
      "completedBy" : {
        "message": "Test2Event",
        "conclusion": "succeeded",
        "name": "Abgeschlossen mit Test2Event"
      }
    },
    {
      "completedBy" : {
        "condition" : "ch.admin.bit.jeap.processcontext.plugin.api.condition.AllTasksInFinalStateProcessCompletionCondition"
      }
    }
  ]
}

=== jeap-admin-ch/jeap-process-context-service/jeap-process-context-repository-template-json/src/test/resources/process/templates/serializer_message_test_template.json
{
  "name": "serializerMessageTestProcess",
  "messages": [
    {
      "messageName": "TestEvent",
      "topicName": "test.topic",
      "correlationProvider": "ch.admin.bit.jeap.processcontext.repository.template.json.stubs.TestCorrelationProvider"
    },
    {
      "messageName": "TestEvent2",
      "topicName": "test2.topic"
    },
    {
      "messageName": "TestEvent3",
      "topicName": "test3.topic",
      "payloadExtractor": "ch.admin.bit.jeap.processcontext.repository.template.json.stubs.TestPayloadExtractor",
      "triggersProcessInstantiation": true
    },
    {
      "messageName": "TestEvent4",
      "topicName": "test4.topic",
      "correlatedBy": {
        "processDataKey": "processDataKey",
        "messageDataKey": "someMessageDataKey"
      },
      "referenceExtractor": "ch.admin.bit.jeap.processcontext.repository.template.json.stubs.TestReferenceExtractor"
    }
  ],
  "tasks": [
    {
      "name": "single-legacy",
      "cardinality": "single"
    },
    {
      "name": "dynamic-legacy",
      "cardinality": "dynamic"
    },
    {
      "name": "defaults"
    },
    {
      "name": "single",
      "lifecycle": "static"
    },
    {
      "name": "single-explicit",
      "lifecycle": "static",
      "cardinality": "single-instance"
    },
    {
      "name": "dynamic",
      "lifecycle": "dynamic"
    },
    {
      "name": "dynamic-multi",
      "lifecycle": "dynamic",
      "cardinality": "multi-instance"
    },
    {
      "name": "observed",
      "lifecycle": "observed",
      "observes": {
        "message": "TestEvent"
      }
    },
    {
      "name": "observedWithCondition",
      "lifecycle": "observed",
      "observes": {
        "domainEvent": "TestEvent",
        "condition": "ch.admin.bit.jeap.processcontext.repository.template.json.TestTaskInstantiationCondition"
      }
    },
    {
      "name": "plannedByEventOrMessage",
      "lifecycle": "dynamic",
      "plannedBy": {
        "message": "TestEvent"
      },
      "taskData": [
        {
          "sourceMessage": "TestEvent",
          "messageDataKeys": ["foo", "bar"]
        }
      ]
    },
    {
      "name": "plannedByEventOrMessageWithCondition",
      "lifecycle": "dynamic",
      "plannedBy": {
        "message": "TestEvent",
        "condition": "ch.admin.bit.jeap.processcontext.repository.template.json.TestTaskInstantiationCondition"
      }
    },
    {
      "name": "completedByDomainEvent",
      "completedBy": {
        "message": "TestEvent"
      },
      "taskData": [
        {
          "sourceMessage": "TestEvent",
          "messageDataKeys": ["foo"]
        }
      ]
    }
  ],
  "processData": [
    {
      "key": "processDataKey",
      "source": {
        "message": "TestEvent4",
        "messageDataKey": "sourceDataKey"
      }
    }
  ],
  "relationSystemId": "ch.test.System",
  "relationPatterns": [
    {
      "subject": {
        "type": "some-type",
        "selector": {
          "processDataKey": "processDataKey",
          "role": "some-role"
        }
      },
      "object": {
        "type": "some-other-type",
        "selector": {
          "processDataKey": "processDataKey"
        }
      },
      "predicateType": "some relationship"
    }
  ],
  "completions": [
    {
      "completedBy": {
        "condition": "ch.admin.bit.jeap.processcontext.plugin.api.condition.AllTasksInFinalStateProcessCompletionCondition"
      }
    },
    {
      "completedBy": {
        "message": "TestEvent4",
        "conclusion": "cancelled",
        "name": "Cancelled because of TestEvent4"
      }
    }
  ],
  "snapshots": [
    {
      "createdOn" : {
        "completion": "any"
      }
    }
  ]
}

=== jeap-admin-ch/jeap-process-context-service/jeap-process-context-scs/src/test/resources/process/templates/pending_messages.json
{
  "name": "pending_messages",
  "tasks": [
    {
      "name": "raceCarRefuel",
      "lifecycle": "dynamic",
      "cardinality": "multi-instance",
      "plannedBy": {
        "message": "Test1Event"
      },
      "completedBy": {
        "message": "Test2Event"
      },
      "taskData": [
        {
          "sourceMessage": "Test1Event",
          "messageDataKeys": [
            "key1"
          ]
        }
      ]
    }
  ],
  "messages": [
    {
      "messageName": "Test1Event",
      "topicName": "topic.test1",
      "payloadExtractor": "ch.admin.bit.jeap.processcontext.testevent.Test1EventPayloadExtractor",
      "correlationProvider": "ch.admin.bit.jeap.processcontext.testevent.TaskTest1EventCorrelationProvider"
    },
    {
      "messageName": "Test2Event",
      "topicName": "topic.test2",
      "correlationProvider": "ch.admin.bit.jeap.processcontext.testevent.TaskTest2EventCorrelationProvider"
    },
    {
      "messageName": "Test3Event",
      "topicName": "topic.test3"
    },
    {
      "messageName": "Test4Event",
      "topicName": "topic.test4",
      "triggersProcessInstantiation": true
    }
  ],
  "completions": [
    {
      "completedBy": {
        "message": "Test3Event",
        "conclusion": "succeeded",
        "name": "Completed by Test3Event"
      }
    }
  ]
}
